import { createRouter as createTanStackRouter } from "@tanstack/react-router";
import { routeTree } from "./routeTree.gen";

// routeTree.gen.ts is generated by the TanStack router plugin on the first
// `vite dev` or `vite build`. It is committed, because `pnpm typecheck` runs
// before `pnpm build` in the Codesphere prepare stage and would otherwise fail
// on a fresh clone.
export function getRouter() {
	return createTanStackRouter({
		routeTree,
		scrollRestoration: true,
		defaultPreload: "intent",
	});
}

declare module "@tanstack/react-router" {
	interface Register {
		router: ReturnType<typeof getRouter>;
	}
}
