import { createRouter as createTanStackRouter } from "@tanstack/react-router";
import { routeTree } from "./routeTree.gen";

// routeTree.gen.ts is generated by the TanStack router plugin on the first
// `vite dev` or `vite build`. It is committed so `pnpm typecheck` works on a
// fresh clone before any build has generated the file.
export function getRouter() {
	return createTanStackRouter({
		routeTree,
		scrollRestoration: true,
		defaultPreload: "intent",
	});
}

declare module "@tanstack/react-router" {
	interface Register {
		router: ReturnType<typeof getRouter>;
	}
}
