dataCenter:
    id: 1
    name: Frankfurt
    city: Karlsruhe
    countryCode: DE
secrets:
    baseDir: /etc/codesphere/secrets
registry:
    server: ""  # //TODO : add repository (ghcr.io) , plus the related secrets in the prod.vaults.yaml
    replaceImagesInBom: false
    loadContainerImages: false
postgres:  # //TODO : replace certifcates, update IP and host details
    mode: install # If OMS installs the cluster, check the docs for external cluster mode
    caCertPem: |
        -----BEGIN CERTIFICATE-----
        MIIDaDCCAlCgAwIBAgIQVzUZ7JMDMmCxclD7gUJoXzANBgkqhkiG9w0BAQsFADBO
        .....       
        L1x5tEJ/QQRcx9clxupNQfhOLNWa5K39NOF21J+CsDuLPWQtpzC7063poGGhzydU
        dPvOoR8SzyEx6yG0
        -----END CERTIFICATE-----
    primary:
        sslConfig:
            serverCertPem: |
                -----BEGIN CERTIFICATE-----
                MIIEdzCCA1+gAwIBAgIRAMYOT3/so3EeAwPkMRFKZ2EwDQYJKoZIhvcNAQELBQAw
                ....
                ZAWYRoRIRzSL9qNQsTYO361/xsmMT22R/ZrXHKw+T/p3UMnIE0JIjuM+eQbUjIb9
                m6YRWOw4AOJcOn8kGoRen7u3WemABkmRpp8zN3Pb0iQvbMb/l+sH/3dIxA==
                -----END CERTIFICATE-----
        ip: 10.20.2.187
        hostname: tf-demo-pr-5-postgres-1
ceph:
    csiKubeletDir: /var/lib/kubelet
    cephAdmSshKey: # // TODO  replace with generated key
        publicKey: |
            ssh-rsa AAAAB3NzaC.....Fa8xBng841ZRrQ==
    nodesSubnet: 127.0.0.1/32   # // TODO : update subnet
    hosts:   # //TODO : add Ceph Nodes, only one can be master.  
        - hostname: ceph-01
          ipAddress: 1.2.3.4
          isMaster: true
        - hostname: ceph-02
          ipAddress: 1.2.3.5
          isMaster: false
    osds:
        - specId: default
          placement:
            host_pattern: '*'
          dataDevices:
  
            size: 350G:450G # //TODO : update disk size, give it range to avoid GB vs GiB issues 
            limit: 1
          dbDevices:
            size: 1G
            limit: 1
kubernetes:
    managedByCodesphere: false  
    apiServerHost: 127.0.0.1 # //TODO replace with  https://abcd.....efg.gr7.eu-central-1.eks.amazonaws.com, the url of the kubernetes api server
    controlPlanes: []
    workers: []
    podCidr: 10.20.8.0/21
    serviceCidr: 172.20.0.0/16 
cluster:
    certificates:  # //TODO : replace with generated certificates
            algorithm: RSA
            keySizeBits: 2048
            certPem: |
                -----BEGIN CERTIFICATE-----
                MIIDczCCAlugAwIBAgIRAMp7m15DjAQscjCDOrdls1QwDQYJKoZIhvcNAQELBQAw
                UzELMAkGA1UEBhMCREUxEjAQBgNVBAcTCUthcmxzcnVoZTETMBEGA1UEChMKQ29k
                .....
                Q5Wg9c4wHKQ38d7f9GfFVcfTrj6SPQ8=
                -----END CERTIFICATE-----
    certManager:
        override:
            cert-manager:
                cainjector:
                    resources:
                        requests:
                            cpu: 0
                            memory: 0
                resources:
                    requests:
                        cpu: 0
                        memory: 0
                startupapicheck:
                    resources:
                        requests:
                            cpu: 0
                            memory: 0
                webhook:
                    replicaCount: 1
                    resources:
                        requests:
                            cpu: 0
                            memory: 0
    trustManager:
        override:
            trust-manager:
                resources:
                    requests:
                        cpu: 0
                        memory: 0
    monitoring:
        prometheus:
            remoteWrite:
                enabled: false
                clusterName: dev
            override:
                kube-prometheus-stack:
                    kube-state-metrics:
                        resources:
                            requests:
                                cpu: 0
                                memory: 0
                    prometheus:
                        prometheusSpec:
                            resources:
                                requests:
                                    cpu: 0
                                    memory: 0
                    prometheus-node-exporter:
                        resources:
                            requests:
                                cpu: 0
                                memory: 0
                    prometheusOperator:
                        resources:
                            requests:
                                cpu: 0
                                memory: 0
        blackboxExporter:
            override:
                prometheus-blackbox-exporter:
                    replicas: 1
                    resources:
                        requests:
                            cpu: 0
                            memory: 0
        pushGateway:
            override:
                prometheus-pushgateway:
                    resources:
                        requests:
                            cpu: 0
                            memory: 0
        loki:
            enabled: true
            override:
                loki:
                    backend:
                        replicas: 1
                        resources:
                            requests:
                                cpu: 0
                                memory: 0
                    canary:
                        replicas: 1
                        resources:
                            requests:
                                cpu: 0
                                memory: 0
                    chunksCache:
                        replicas: 1
                        resources:
                            requests:
                                cpu: 0
                                memory: 0
                    gateway:
                        replicas: 1
                        resources:
                            requests:
                                cpu: 0
                                memory: 0
                    read:
                        replicas: 1
                        resources:
                            requests:
                                cpu: 0
                                memory: 0
                    resultsCache:
                        replicas: 1
                        resources:
                            requests:
                                cpu: 0
                                memory: 0
                    write:
                        replicas: 1
                        resources:
                            requests:
                                cpu: 0
                                memory: 0
        grafana:
            enabled: true
        grafanaAlloy:
            enabled: true
    gateway:
        serviceType: LoadBalancer
        override:
            ingress-nginx:
                controller:
                    replicaCount: 1
                    resources:
                        requests:
                            cpu: 0
                            memory: 0
    publicGateway:
        serviceType: LoadBalancer
        override:
            ingress-nginx:
                controller:
                    replicaCount: 1
                    resources:
                        requests:
                            cpu: 0
                            memory: 0
            nginx:
                replicaCount: 1
                resources:
                    requests:
                        cpu: 0
                        memory: 0
    pgOperator:
        enabled: true
        override:
            cloudnative-pg:
                resources:
                    requests:
                        cpu: 0
                        memory: 0
    BarmanCloudPluginConfig:
        enabled: true
        override:
            plugin-barman-cloud:
                resources:
                    requests:
                        cpu: 0
                        memory: 0
    rgwLoadBalancer:
        enabled: true
        override:
            replicas: 1
metallb:
    enabled: false
    pools: []
codesphere:
    domain: aws-demo.codesphere-demo.com
    workspaceHostingBaseDomain: 1.aws-demo.codesphere-demo.com
    publicIp: ""  # //TODO: add public IP of the public-gateway-controller and rerun the installer (the ip is only known after the first installation
    certIssuer: # 
        - selfsigned
    customDomains:
        cNameBaseDomain: aws-demo.codesphere-demo.com
    dnsServers:
        - 8.8.8.8
        - 1.1.1.1
    internal:  # //TODO: Check the list of entries in internal, preview and features. These are Usecase and Version dependendant 
      - headless-service
      - vcluster
      - custom-service-image
      - ms-in-ls
    preview:
      secret-management: true
      sub-path-mount: true
      workspace-ssh: true
    features:
      dev-domains-port: true
    workspaceImages:
        agent:
            bomRef: workspace-agent-24.04
    deployConfig:
        images:
            ubuntu-24.04:
                name: Ubuntu 24.04
                supportedUntil: "2028-05-31"
                flavors:
                    default:
                        image:
                            bomRef: workspace-agent-24.04
                        pool:
                            1: 1
    plans:
        hostingPlans:
            1:
                cpuTenth: 10
                gpuParts: 0
                memoryMb: 2048
                storageMb: 20480
                tempStorageMb: 1024
        workspacePlans:
            1:
                name: Standard
                hostingPlanId: 1
                maxReplicas: 3
                onDemand: true
    managedServices:
        - name: postgres
          version: v1
        - name: babelfish
          version: v1
        - name: s3
          version: v1
        - name: virtual-k8s
          version: v1
        - name: ferretdb
          version: v0
    override:
        global:
            frontendGateway:
                requests:
                    cpu: 0
                    memory: 0
            services:
                auth_service:
                    replicas: 2
                    requests:
                        cpu: 0
                        memory: 0
                deployment_service:
                    replicas: 2
                    requests:
                        cpu: 0
                        memory: 0
                error_page_server:
                    requests:
                        cpu: 0
                        memory: 0
                ide_frontend:
                    requests:
                        cpu: 0
                        memory: 0
                ide_service:
                    requests:
                        cpu: 0
                        memory: 0
                marketplace:
                    requests:
                        cpu: 0
                        memory: 0
                payment_service:
                    requests:
                        cpu: 0
                        memory: 0
                public_api_service:
                    replicas: 2
                    requests:
                        cpu: 0
                        memory: 0
                team_service:
                    replicas: 2
                    requests:
                        cpu: 0
                        memory: 0
                workspace_proxy:
                    requests:
                        cpu: 0
                        memory: 0
                workspace_service:
                    replicas: 2
                    requests:
                        cpu: 0
                        memory: 0
    openBao: #optional sectoin
        engine: cs-secrets-engine
        uri: "" # the ULR of your openbao server
        user: codesphere
pcApps:
  applications:
    kyverno:
      enabled: true
    kyverno-policies:
      enabled: true
    blackbox-exporter:
      enabled: true
    ssh-workspace-proxy:
      enabled: true
      valuesObject:
        otel:
          endpoint: "http://otel-collector.codesphere.svc.cluster.local:4318"
          appLabel: "otel-collector"
        service:
          enabled: true
          type: LoadBalancer
          externalTrafficPolicy: Local
   
managedServiceBackends:
    postgres:
        override:
            replicas: 1
            resources:
                requests:
                    cpu: 0
                    memory: 0
    s3:
        override:
            replicas: 1
            resources:
                requests:
                    cpu: 0
                    memory: 0
operations:
  codesphere: 0
  skip:
    - load-container-images
    